import { readFileSync, statSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

function read(path: string) {
  return readFileSync(resolve(process.cwd(), path), "utf8");
}

describe("Weekly Roundup surface", () => {
  it("keeps the roundup separate from the bottom Insights navigation", () => {
    const app = read("src/App.tsx");

    expect(app).toContain("Weekly roundup");
    expect(app).toContain('openDrawer("roundup")');
    expect(app).toContain('/api/roundup?');
    expect(app).not.toContain("tab-roundup");
  });

  it("removes the non-interactive pulse markers while retaining sighting clicks", () => {
    const app = read("src/App.tsx");
    const styles = read("src/styles.css");

    expect(app).not.toContain("flock-pulse");
    expect(styles).not.toContain("flock-pulse");
    expect(app).toContain('marker.on("click", () => selectSighting(feature))');
  });

  it("uses Flockline attribution in all reader-facing generation copy", () => {
    const publicCopy = [read("src/App.tsx"), read("src/Methodology.tsx")].join("\n");

    expect(publicCopy).toContain("Generated by Flockline");
    expect(publicCopy).not.toContain("Written by Claude");
    expect(publicCopy).not.toContain("Claude writes");
  });

  it("publishes a cache-busted X card with explicit image metadata", () => {
    const html = read("index.html");
    const card = statSync(resolve(process.cwd(), "public", "flockline-social-v2.jpg"));

    expect(html).toContain("https://flockline.app/flockline-social-v2.jpg?v=20260818");
    expect(html).toContain('property="og:image:type" content="image/jpeg"');
    expect(html).toContain('property="og:image:width" content="1200"');
    expect(html).toContain('property="og:image:height" content="630"');
    expect(html).toContain('name="twitter:image:alt"');
    expect(card.isFile()).toBe(true);
    expect(card.size).toBeGreaterThan(50_000);
  });

  it("serves an explicit crawler policy for social previews", () => {
    const robots = read("public/robots.txt");

    expect(robots).toContain("User-agent: Twitterbot\nAllow: /");
    expect(robots).toContain("User-agent: *\nAllow: /");
  });
});
